/**
 * Mapeamento código interno -> sigla DataJud.
 * Mantido fora dos adapters para evitar ciclos de importação.
 */
export const DATAJUD_TRIBUNAIS: Record<string, string> = {
  STF: 'stf',
  STJ: 'stj',
  TST: 'tst',
  TSE: 'tse',
  STM: 'stm',

  TJSP: 'tjsp',
  TJRJ: 'tjrj',
  TJMG: 'tjmg',
  TJRS: 'tjrs',
  TJBA: 'tjba',
  TJPR: 'tjpr',
  TJSC: 'tjsc',
  TJGO: 'tjgo',
  TJDFT: 'tjdft',
  TJPE: 'tjpe',
  TJCE: 'tjce',
  TJES: 'tjes',
  TJMS: 'tjms',
  TJMT: 'tjmt',
  TJPB: 'tjpb',
  TJRN: 'tjrn',
  TJAL: 'tjal',
  TJSE: 'tjse',
  TJPI: 'tjpi',
  TJMA: 'tjma',
  TJPA: 'tjpa',
  TJAM: 'tjam',
  TJAP: 'tjap',
  TJRO: 'tjro',
  TJRR: 'tjrr',
  TJAC: 'tjac',
  TJTO: 'tjto',

  TRF1: 'trf1',
  TRF2: 'trf2',
  TRF3: 'trf3',
  TRF4: 'trf4',
  TRF5: 'trf5',
  TRF6: 'trf6',

  ...Object.fromEntries(Array.from({ length: 24 }, (_, i) => [`TRT${i + 1}`, `trt${i + 1}`])),

  TREAC: 'tre-ac',
  TREAL: 'tre-al',
  TREAM: 'tre-am',
  TREAP: 'tre-ap',
  TREBA: 'tre-ba',
  TRECE: 'tre-ce',
  TREDF: 'tre-df',
  TREES: 'tre-es',
  TREGO: 'tre-go',
  TREMA: 'tre-ma',
  TREMG: 'tre-mg',
  TREMS: 'tre-ms',
  TREMT: 'tre-mt',
  TREPA: 'tre-pa',
  TREPB: 'tre-pb',
  TREPE: 'tre-pe',
  TREPI: 'tre-pi',
  TREPR: 'tre-pr',
  TRERJ: 'tre-rj',
  TRERN: 'tre-rn',
  TRERO: 'tre-ro',
  TRERR: 'tre-rr',
  TRERS: 'tre-rs',
  TRESC: 'tre-sc',
  TRESE: 'tre-se',
  TRESP: 'tre-sp',
  TRETO: 'tre-to',

  TJMMG: 'tjmmg',
  TJMRS: 'tjmrs',
  TJMSP: 'tjmsp',
};
